---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: example-app-2
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/VLXMDE/td-app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example-app-2
  namespace: default
spec:
  interval: 1m0s
  path: "./example-app-2/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: example-app-2